name: Build ISO

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-iso:
    name: Build Custom Arch ISO
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            archiso \
            git \
            base-devel \
            wget \
            curl \
            dosfstools \
            squashfs-tools \
            mtools \
            jq

          pacman-key --init
          pacman-key --populate archlinux

      - name: Add Garch Repo
        run: |
          echo '[garch-repo]' >> /etc/pacman.conf
          echo 'SigLevel = Optional TrustAll' >> /etc/pacman.conf
          echo 'Server = https://gitlab.com/Kingcat5503/garch-repo/-/raw/main/$arch' >> /etc/pacman.conf
          pacman -Sy || true

      - name: Add Cachyos Repo
        run: |
          sudo pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
          sudo pacman-key --lsign-key F3B607488DB35A47
          sudo pacman --noconfirm -U 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-20240331-1-any.pkg.tar.zst' \
          'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-22-1-any.pkg.tar.zst'
          echo '[cachyos]' >> /etc/pacman.conf
          echo 'Include = /etc/pacman.d/cachyos-mirrorlist' >> /etc/pacman.conf
          sudo pacman -Sy || true

      - name: Copy releng profile
        run: |
          cp -r /usr/share/archiso/configs/releng ./releng

      - name: Build ISO
        run: |
          mkarchiso -v -w work -o out ./releng

      - name: Upload ISO artifact
        id: artifact_upload
        uses: actions/upload-artifact@v4
        with:
          name: govix-archiso
          path: out/*.iso
          retention-days: 15