name: Govix Controller

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: "select what to do"
        options:
          - build
          - publish
          - both
        required: true
        default: build

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Read action input or auto-mode
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "mode=build" >> $GITHUB_OUTPUT
          else
            echo "mode=${{ github.event.inputs.action }}" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Build Workflow
        if: steps.vars.outputs.mode == 'build' || steps.vars.outputs.mode == 'both'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build ISO
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Publish Workflow
        if: steps.vars.outputs.mode == 'publish' || steps.vars.outputs.mode == 'both'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Publish ISO
          token: ${{ secrets.GITHUB_TOKEN }}
