name: Govix Pipeline Controller

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  read-config:
    name: Read workflow.conf
    runs-on: ubuntu-latest
    outputs:
      BUILD: ${{ steps.out.outputs.BUILD }}
      RELEASE: ${{ steps.out.outputs.RELEASE }}
      PAGES: ${{ steps.out.outputs.PAGES }}
      TAG_FORMAT: ${{ steps.out.outputs.TAG_FORMAT }}
      RELEASE_TITLE: ${{ steps.out.outputs.RELEASE_TITLE }}
      RELEASE_BODY: ${{ steps.out.outputs.RELEASE_BODY }}

    steps:
      - uses: actions/checkout@v4

      - id: out
        run: |
          CONF=".github/workflow.conf"

          # Read booleans
          echo "BUILD=$(grep '^BUILD=' $CONF | cut -d= -f2)" >> $GITHUB_OUTPUT
          echo "RELEASE=$(grep '^RELEASE=' $CONF | cut -d= -f2)" >> $GITHUB_OUTPUT
          echo "PAGES=$(grep '^PAGES=' $CONF | cut -d= -f2)" >> $GITHUB_OUTPUT

          # Read release vars
          echo "TAG_FORMAT=$(grep '^TAG_FORMAT=' $CONF | cut -d= -f2- | tr -d '\"')" >> $GITHUB_OUTPUT
          echo "RELEASE_TITLE=$(grep '^RELEASE_TITLE=' $CONF | cut -d= -f2- | tr -d '\"')" >> $GITHUB_OUTPUT
          echo "RELEASE_BODY=$(grep '^RELEASE_BODY=' $CONF | cut -d= -f2- | tr -d '\"')" >> $GITHUB_OUTPUT


  run-build:
    name: Trigger Build Workflow
    needs: read-config
    if: needs.read-config.outputs.BUILD == 'true'
    uses: ./.github/workflows/build.yml


  run-release:
    name: Trigger Release Workflow
    needs: [read-config, run-build]
    if: needs.read-config.outputs.RELEASE == 'true'
    uses: ./.github/workflows/release.yml
    with:
      TAG_FORMAT: ${{ needs.read-config.outputs.TAG_FORMAT }}
      RELEASE_TITLE: ${{ needs.read-config.outputs.RELEASE_TITLE }}
      RELEASE_BODY: ${{ needs.read-config.outputs.RELEASE_BODY }}


  run-pages:
    name: Trigger Pages Workflow
    needs: [read-config, run-release]
    if: needs.read-config.outputs.PAGES == 'true'
    uses: ./.github/workflows/pages.yml
