name: Publish ISO to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ publish-pages ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download ISO artifact from Build Workflow
        uses: actions/download-artifact@v4
        with:
          name: govix-archiso
          path: iso/

      - name: Prepare gh-pages directory
        run: |
          rm -rf gh-pages
          mkdir -p gh-pages
          cp iso/*.iso gh-pages/

          # generate simple index.html
          echo "<h1>Govix ISO Download</h1>" > gh-pages/index.html
          echo "<p>Latest Build:</p>" >> gh-pages/index.html
          echo "<a href='./$(ls iso)' download>Download ISO</a>" >> gh-pages/index.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages
          force_orphan: true
